### ISSUE TITLE
Error compiling basicExample for STM32

### ISSUE THREAD

**Issue by AmyTheCute** [miguel5612/ThermistorLibrary#1]
> Arduino: 1.8.9 (Windows 10), Board: "Generic STM32F103C series, STM32F103C8 (20k RAM. 64k Flash), STM32duino bootloader, 72Mhz (Normal), Smallest (default)"
> 
> F:\Libraries\Documents\Arduino\libraries\Arduino-ThermistorLibrary-master\thermistor.cpp: In member function 'float thermistor::analog2temp()':
> 
> F:\Libraries\Documents\Arduino\libraries\Arduino-ThermistorLibrary-master\thermistor.cpp:41:38: error: ISO C++ forbids comparison between pointer and integer [-fpermissive]
> 
>      for (i = 1; i < heater_ttbl_map[e]; i++) {
> 
>                                       ^
> 
> exit status 1
> Error compiling for board Generic STM32F103C series.
> 
> This report would have more information with
> "Show verbose output during compilation"
> option enabled in File -> Preferences.
> 

I am trying to compile the example for my STM32F103C but I get this error. I am simply using the example. works perfectly with Arduino Uno

**Comment by miguel5612** [comment]
Morning.
We regret the fact that you have not compiled the code, we have reviewed and the problem is due to an error in your compiler for the selected board (this error occurs because he does not interpret the source code correctly), we recommend using an arduino one / mega for processing and data acquisition and the Generic STM32F103C series, STM32F103C8 as a display card communicated through serial port.
Our target architecture is AVR and your processor is ARM, we have fixed this bug in the lib.prop file. We thank you for your Issue and apologize for the inconvenience caused.

Translated with www.DeepL.com/Translator
